# Site settings
title: Blog Juberth
email: gfhfgh
description: > # this means to ignore newlines until "baseurl:"
  Blog con fines educativos creado con Jekyll
  Blog para pruebas de la clase de Ingenieria de Software 
  Gracias por su visita.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://garciajarrison.github.io/" # the base hostname & protocol for your site
twitter_username: juberthquintero
github_username:  juberth24

# Build settings
markdown: kramdown
